name: GitHub Actions Demo
run-name: CI
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, linux, x64]
    steps:
<<<<<<< HEAD
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ðŸ This job"s status is ${{ job.status }}."
=======
      - run: echo "Running lint"
      - run: npm run lint
      - run: echo "Running test"
      - run: npm run test
      - run: echo "Running build"
      - run: npm run build
      - run: echo "ðŸ This job's status is ${{ job.status }}."
>>>>>>> 3ac8aa37eb9eb698d1d2aa73f7638065f58b284d
