name: GitHub Actions Demo
run-name: CI
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on:  [self-hosted, linux, x64]
    steps:
      - run: echo "Running lint"
      - run: npm run lint
      - run: echo "Running test"
      - run: npm run test
      - run: echo "Running build"
      - run: npm run build
      - run: echo "ğŸ This job's status is ${{ job.status }}."
